### ISSUE TITLE
English frequency list

### ISSUE THREAD

**Issue by Geniusssmit** [themoeway/kaikki-to-yomitan#10]
I just wanted to ask if there is any English frequency list compatible? The one I uploaded here can't be imported, it gives an error
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/24941285/24ab5f35-6430-45cf-bf19-69bcf4458db2)

[yzk-freq-en.zip](https://github.com/themoeway/kaikki-to-yomitan/files/14440270/yzk-freq-en.zip)

**Comment by StefanVukovic99** [comment]
[yzk-freq-en-v3.zip](https://github.com/themoeway/kaikki-to-yomitan/files/14440295/yzk-freq-en-v3.zip)
This one should work.

For posterity, to get a `yzk-freq` dict to work on yomitan, unzip it, in index.json
```json
{
    "title": "yzk-freq-en",
    "revision": "2024.02.28",
    "format": 4,
    "sequenced": true
}
```
change the 4 to a 3, then recompress the files again and it should work.

**Comment by BilderLoong** [comment]
Also, for French and German:

[yzk-freq-de-v3.zip](https://github.com/themoeway/kaikki-to-yomitan/files/14456063/yzk-freq-de-v3.zip)
[yzk-freq-fr-v3.zip](https://github.com/themoeway/kaikki-to-yomitan/files/14456064/yzk-freq-fr-v3.zip)
