### ISSUE TITLE
Add Tagalog Support (tl)

### ISSUE THREAD

**Issue by namakusan** [themoeway/kaikki-to-yomitan#105]
Is it possible to add Tagalog? Theres some wikitionary data on Tagalog, and I would love to use it with Yomitan.

**Comment by StefanVukovic99** [comment]
Sure, here you go:
[kty-tl-en-ipa.zip](https://github.com/user-attachments/files/16173459/kty-tl-en-ipa.zip)
[kty-tl-en.zip](https://github.com/user-attachments/files/16173460/kty-tl-en.zip)

**Comment by namakusan** [comment]
Thank you!
