### ISSUE TITLE
en-en dictionary gives an error

### ISSUE THREAD

**Issue by NeonGooRoo** [themoeway/kaikki-to-yomitan#11]
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/123720895/966bcc87-598a-4460-a9b9-72573a931fcd)

Error: Dictionary has invalid data in 'term_bank_36.json'

problem persists on different browsers

**Comment by StefanVukovic99** [comment]
(needs yomitan 24.01.20.0)
