### ISSUE TITLE
Add Latvian support

### ISSUE THREAD

**Issue by zh-7** [themoeway/kaikki-to-yomitan#119]
Would it be possible to add this language?

**Comment by StefanVukovic99** [comment]
Sure! Here you go:
[kty-lv-en.zip](https://github.com/user-attachments/files/16417284/kty-lv-en.zip)
[kty-lv-en-ipa.zip](https://github.com/user-attachments/files/16417283/kty-lv-en-ipa.zip)

**Comment by zh-7** [comment]
Thank you!!
