### ISSUE TITLE
Yomitan doesn't understand words with capital letters and different forms.

### ISSUE THREAD

**Issue by NeonGooRoo** [themoeway/kaikki-to-yomitan#12]
For example. the word "dictionary" is scanned, but "Dictionary" or "dictionaries" don't. It is very convenient to use. I hope this is fixable. Amazing work nevertheless.

![image](https://github.com/themoeway/kaikki-to-yomitan/assets/123720895/c0eab7f5-4a1d-4dfd-873f-056d8b79fcf2)
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/123720895/212884a6-ecfc-46f9-aa1a-d4ccc9b7b90d)

**Comment by StefanVukovic99** [comment]
(needs yomitan 24.02.23.0)
