### ISSUE TITLE
Missing "Preposition" entries (DE-EN)

### ISSUE THREAD

**Issue by emanuelps2708** [themoeway/kaikki-to-yomitan#125]
Hi Ponfrit, sorry it's me again, it appears that kaikki disregards all preposition entries, I noticed it with prepositions like "an", "mit", "in" and  "pro".
![Screenshot from 2024-08-03 18-11-25](https://github.com/user-attachments/assets/525b01f0-453d-400e-8ea0-8ede04f466c4)
![image](https://github.com/user-attachments/assets/c8c7839b-f264-4ec8-8ca8-7cdffae5275c)

**Comment by StefanVukovic99** [comment]
I've opened an issue, https://github.com/tatuylonen/wiktextract/issues/760, but things like this pop up often enough maybe I'll do something on our side to prevent them.
