### ISSUE TITLE
Possibly add Japanese edition

### ISSUE THREAD

**Issue by emanuelps2708** [themoeway/kaikki-to-yomitan#143]
Hi Ponfrit,

I hope you're doing well! I noticed that Kaikki recently added Japanese and Polish editions of Wiktionary. If it would be possible to add the Japanese edition, that would be wonderful.

Thanks so much for all your hard work, I really appreciate it! ;)

**Comment by StefanVukovic99** [comment]
Hadn't heard of this, thanks for the tip! Will get on it ASAP.
