### ISSUE TITLE
How to run V4 to V3 script

### ISSUE THREAD

**Issue by FoundNull** [themoeway/kaikki-to-yomitan#15]
"Hello! I've been trying to run the v4 to v3 script for a few days now. I'm trying to use it because every time I try to change the format of a dictionary manually, Yomichan displays this:

ExtensionError: Dictionary has invalid data in 'index.json'

I'm having a difficult time understanding how to properly execute the script." Thanks in advance for the help

**Comment by StefanVukovic99** [comment]
closing since #16 fixes the comment with instructions (and we solved this particular case on discord)
