### ISSUE TITLE
is it possible to provide more detailed instruction?

### ISSUE THREAD

**Issue by saufall** [themoeway/kaikki-to-yomitan#21]
I unfortunately have no coding knowledge, and I would like to scrape Italian-Italian wiktionary dictionary data for learning italian.
I tried the method in readme.md but i encountered some hiccups.

from readme.md:

Basic Run
Create a .env file based on .env.example.
(how does this work? what are 
DEBUG_WORD=sehen
DICT_NAME=abc
MAX_MEMORY_MB=8192
those three variables for? would this work?
changed to
"DEBUG_WORD=sehen1
DICT_NAME=It-It
MAX_MEMORY_MB=8192"
)

##If your language is not in languages.json, add it.

Run ./auto.sh German English.

(when I run ./auto.sh Italian Italian, a window pops up asking me to choose the program to open .sh, which is the unintended behaviour as i would like to execute the script instead. so what is the correct thing to do here?)

Dictionaries should be in data/language/de/en.
(nothing like that appeared.)

**Comment by StefanVukovic99** [comment]
Unfortunately Italian dictionaries are not yet supported in [wiktextract](https://kaikki.org/dictionary/rawdata.html).
