### ISSUE TITLE
Add Dictionaries to Readme 

### ISSUE THREAD

**Issue by brishtibheja** [themoeway/kaikki-to-yomitan#37]
Currently IMO it's too hard to search for a particular dictionary in the releases page. ja-es/en-de such notations also don't make sense for the common folks. Can the links to these dicts not be in the Readme? I am also trying to send this to another person who's trying to create decks for multiple languages here and I'm afraid he'll be lost.

I'm thinking something that resembles Marv's repo. Just add the dictionaries under the language name they belong to. I'll be glad if something like that is done.

Thanks for your incredible work!

**Comment by StefanVukovic99** [comment]
https://github.com/themoeway/kaikki-to-yomitan/releases/latest link should always point to the latest release, but  I don't see a way to link each individual dict so that the link updates on release... The release notes there should be enough to understand the notation and whatnot i think.

**Comment by MarvNC** [comment]
If the filename stays the same, you can link using `latest`. I prefer having date info in the filename personally, could be possible to generate a markdown table in the release or something 🤔

**Comment by StefanVukovic99** [comment]
Got something going with a [downloads page](https://github.com/themoeway/kaikki-to-yomitan/blob/master/downloads.md). Doesn't look very pretty though, any ideas?

**Comment by brishtibheja** [comment]
Lists are better than tables. Here I need to track the column and then find the row or vice versa. I am thinking of a list with say, Japanese as a header and every jp-x dictionary listed under it. Also, please don't use the dictionary names in hyperlink. I think they are distracting.

**Comment by StefanVukovic99** [comment]
If it was a list I think it would be too long and require too much scrolling around. I think the way the tables look now is ok, so closing this.
