### ISSUE TITLE
Add "Utilisé à tort"(Wrongly used) raw tag directly to the definition

### ISSUE THREAD

**Issue by Ceynou** [themoeway/kaikki-to-yomitan#40]
I say directly to the definition because tags seem to be ignored when converted to a yomitan format.
So here's the problem, there is this word in french, "avatar" which DOESN'T mean and shouldn't be used as misaventure/unlucky happening, but with kty dict we will never know that it's wrong.
Luckily there is this raw tag "Wrongly used", but I can't really agree with tag "broadly"
[kaikki](https://kaikki.org/frwiktionary/Fran%C3%A7ais/meaning/a/av/avatar.html#fr-avatar-fr-noun-01XTXSAu)
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/41862916/37ba5247-1f7f-42a0-becf-3aaf20f41101)
[wiktionary](https://fr.wiktionary.org/wiki/avatar)
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/41862916/34b0e453-d84e-4c35-a704-5bc76c8fad29)
yomitan's
```json
  [
    "avatar",
    "",
    "",
    "noun",
    0,
    [
      "Dans la religion hindouiste, chacune des incarnations du dieu Vishnou.",
      "Métamorphose, transformation d’un objet ou d’un individu qui en a déjà subi plusieurs.",
      "Mésaventure, malheur.",
      "Apparence que prend une personne dans un environnement graphique informatique (image dans un forum internet ou un clavardoir, objet 3D dans un univers virtuel). Cette image peut illustrer autre chose que l’utilisateur lui-même.",
      "Personnage ou objet de synthèse évoluant dans un décor réel."
    ],
    0,
    ""
  ],
  ```

**Comment by StefanVukovic99** [comment]
![Screenshot from 2024-05-16 12-11-02](https://github.com/themoeway/kaikki-to-yomitan/assets/24891609/8b06a14b-1fd8-4557-82eb-f92a70590112)
(When you hover or click on the tag, the full `Utilise a tort` is shown)
Fixed dict [here](https://anonymfile.com/r10ja/kty-fr-fr.zip) (will be included in the next release)

**Comment by StefanVukovic99** [comment]
Also want to note that tags need to be whitelisted to included in the converted dictionary, so when you find more tags that should be added make an issue, or add them to `data/language/target-language-tags/fr/tag_bank_term.json` in a PR.

**Comment by Ceynou** [comment]
Thank you, I'll download the kaikki json, generate a list of the raw tags and get back to you in a PR.

**Comment by StefanVukovic99** [comment]
If you run this converter, for French to French, after conversion there will be a skippedTermTags file, sorted by frequency, maybe that can save you some trouble. I should also be able to send you that file in a couple hours.

**Comment by StefanVukovic99** [comment]
[skippedTermTags.json](https://github.com/themoeway/kaikki-to-yomitan/files/15337837/skippedTermTags.json)
Something breaks for big lists, so there's some wacky numbers at the start.
