### ISSUE TITLE
Esperanto

### ISSUE THREAD

**Issue by Setup2134** [themoeway/kaikki-to-yomitan#51]
Is it possible for esperanto to be added at some point? I think it would be a very good language to add, especially since esperanto is already easy to learn, being able to use yomitan with an esperanto dictionary would be a godsend

**Comment by StefanVukovic99** [comment]
Sure, here you go.
[kty-eo-en.zip](https://github.com/user-attachments/files/15521969/kty-eo-en.zip)
[kty-eo-en-ipa.zip](https://github.com/user-attachments/files/15521968/kty-eo-en-ipa.zip)
It should be included in releases starting from the next one.
