### ISSUE TITLE
Add czech

### ISSUE THREAD

**Issue by Setup2134** [themoeway/kaikki-to-yomitan#53]
Czech wiktionary id assume is quite small based on the graphic, but it would be really great if possibly added; i don't see it in the releases despite it being on the graphic

**Comment by StefanVukovic99** [comment]
Here they are:
[kty-cs-en-ipa.zip](https://github.com/user-attachments/files/15533737/kty-cs-en-ipa.zip)
[kty-cs-en.zip](https://github.com/user-attachments/files/15533738/kty-cs-en.zip)

I think for the graph I just took the languages from the top of https://kaikki.org/dictionary/, skipping the ones that seemed to be outliers. I should probably just add a bunch of languages to the next release, the github action takes [~1h40](https://github.com/themoeway/kaikki-to-yomitan/actions/workflows/release.yml) and we can go up to 6 hours.
