### ISSUE TITLE
Request: Arrange dictionary definitions in list form

### ISSUE THREAD

**Issue by ginger-aleeeee** [themoeway/kaikki-to-yomitan#59]
As shown in the image, the definitions in the dictionary entries are presented in a form that is difficult to read. Is there any way to change the dictionary files so that they are presented in a list form (like the Latin example image found in Releases) rather than as one text block? 

![firefox_YlaMjtFk0M](https://github.com/themoeway/kaikki-to-yomitan/assets/172294461/532f2db8-3be2-4765-a043-4f1d36089a11)
This is what I am seeing from the fr-fr deck. 

![320418874-c5588111-3d4a-4fd8-b3f3-35d33ed5741d](https://github.com/themoeway/kaikki-to-yomitan/assets/172294461/26524b9e-a17b-4280-be77-69b6ece9fa75)
This is the format I am requesting

**Comment by StefanVukovic99** [comment]
The only difference should be in the `Compact glossaries` setting in Yomitan, yours looks on:
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/24891609/de49971f-c95a-4f00-a3fa-cd5b57c33179)

**Comment by ginger-aleeeee** [comment]
Oh, that would do it. I thought that this option had a different function, my mistake!
