### ISSUE TITLE
Missing declensions, meanings and strange formatting

### ISSUE THREAD

**Issue by Setup2134** [themoeway/kaikki-to-yomitan#60]
I have been using a czech dictionary file from the repository for a while now and i've noticed some issues with thins on the main wiktionary website not appearing in the yomitan dictionaries

Some declensions (like the Nominative Plural form for example) seem to be missing
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/138363522/aea3fd6e-9278-4092-9f05-addda0640c3b)
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/138363522/db7df8fa-ce52-4007-a8ac-eb2e334be84b)

Some definitions (like pro "for") or the definition for "z" (doesn't appear at all) are missing
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/138363522/fa0805fa-3e27-4c14-8116-e6ec50be1375)
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/138363522/b2507ae5-6b6e-4107-962e-77afd3bfe511)

Strange formatting for some conjugations (like past active participle being split into three
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/138363522/57372f9c-4ec5-4956-847b-e1249dc490ea)

There may be some others i've forgotten
Other than these issues i'm really liking these dictionaries! very useful for applying yomitan to other languages easily and helps a lot with language learning.
Thanks!

**Comment by StefanVukovic99** [comment]
[kty-cs-en-ipa.zip](https://github.com/user-attachments/files/15786810/kty-cs-en-ipa.zip)
[kty-cs-en.zip](https://github.com/user-attachments/files/15786811/kty-cs-en.zip)
These should have 2 of the issues fixed, we'll wait to hear back from the kaikki guys about the "missing" words.
