### ISSUE TITLE
Add Simple English Wiktionary

### ISSUE THREAD

**Issue by emanuelps2708** [themoeway/kaikki-to-yomitan#64]
Hi Ponfrit, I think it would be great to have Simple English Wiktionary, I looked at the Wikiextract repo and I noticed that there's a pr that hasn't been merged about that version so I'm not sure if it would be better to open an issue there.

**Comment by StefanVukovic99** [comment]
I've noticed that PR, but it looks pretty stale. Nothing we can do here unless/until they release a Simple English edition.

**Comment by emanuelps2708** [comment]
Ok, I understand ponfrit, thank you ;)
