### ISSUE TITLE
Is it possible to have EN-ID?

### ISSUE THREAD

**Issue by kreindo** [themoeway/kaikki-to-yomitan#68]
i wan

**Comment by StefanVukovic99** [comment]
Here's a small dict from the english wiktionary's translations data: [kty-en-id-gloss.zip](https://github.com/user-attachments/files/15815147/kty-en-id-gloss.zip). To get the id wiktionary's data would require someone adding id to kaikki - https://github.com/tatuylonen/wiktextract/discussions/651
