### ISSUE TITLE
Kannada dictionary

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/kaikki-to-yomitan#81]
What would it take to get a kannada-English dictionary? Seems like [wikitionary](https://kn.wiktionary.org/) has 100k+ entries which seems sufficient to create something new

**Comment by StefanVukovic99** [comment]
[kty-kn-en-ipa.zip](https://github.com/user-attachments/files/15932774/kty-kn-en-ipa.zip)
[kty-kn-en.zip](https://github.com/user-attachments/files/15932775/kty-kn-en.zip)
Basically takes a single line, see #73. But may require tweaks if something's not right.
