### ISSUE TITLE
Add monolingual descriptions for deinflection information

### ISSUE THREAD

**Issue by peldas** [themoeway/kaikki-to-yomitan#86]
This may just be an issue for Korean as the algorithm deinflections are all listed in Korean, but it's quite jarring to have to read both Korean and English deinflection information. I think it would be better to match how Yomitan is doing it and make the information monolingual.
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/13115959/42c043d5-7aa0-4d35-9cb5-4a95840a85fb)

**Comment by StefanVukovic99** [comment]
I think the algorithm deinflection is quite exhaustive in yomitan, so maybe you can just turn off the dict deinflections from the kty dict:
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/24891609/f015ecd4-45b8-4187-befc-7c7ce6d6c01a)
Translating the english wikt's info to korean sounds messy and would require knowing some korean to start with.

**Comment by peldas** [comment]
Wasn't aware you could turn these off per-dictionary, thanks!
