### ISSUE TITLE
Split out definitions for readability

### ISSUE THREAD

**Issue by peldas** [themoeway/kaikki-to-yomitan#87]
I think when there are more than ten definitions it gets a bit cluttered and hard to read – I would prefer to see these in a list so my eyes can skim vertically.
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/13115959/b790d9d1-1ed1-41b0-9877-75d7b430fa57)

**Comment by StefanVukovic99** [comment]
same as #59 ?

**Comment by peldas** [comment]
You're right, thank you. Just like the other person I thought the option did something different as well.
