### ISSUE TITLE
Mongolian Support (kh)

### ISSUE THREAD

**Issue by blu3l1fe** [themoeway/kaikki-to-yomitan#88]
Any possibility Mongolian could be added in Cyrllic script (khalkha dialect, the standard language of the republic of Mongolia)? There is quite a bit of wikitionary data for it and I would love to use it with Yomitan.

**Comment by StefanVukovic99** [comment]
Here you go:
[kty-mn-en-ipa.zip](https://github.com/user-attachments/files/16021320/kty-mn-en-ipa.zip)
[kty-mn-en.zip](https://github.com/user-attachments/files/16021321/kty-mn-en.zip)
