### ISSUE TITLE
Error while importing some dictionaries

### ISSUE THREAD

**Issue by fruitports** [themoeway/kaikki-to-yomitan#9]
Trying to import kty-id-en.zip into Yomitan on Kiwi Browser or PC Firefox returns "Error: Dictionary has invalid data in 'term_bank_1.json'"

kty-pt-en.zip - "Error: Dictionary has invalid data in 'term_bank_10.json'"

I also tried to import kty-id-en-ipa.zip and kty-fr-de.zip and found no errors.

**Comment by StefanVukovic99** [comment]
Looks like the yomitan version in the Mozilla Add-ons Browser is [23.12.29.0](https://addons.mozilla.org/en-US/firefox/addon/yomitan/) and the dictionary format used here requires [24.01.20.0](https://github.com/themoeway/yomitan/releases/tag/24.01.20.0).

**Comment by phamthaison1207** [comment]
currently as of 10/3/2024 Yomitan (development build) 24.2.26.0, 3 dictionaries remain affected by this error: macmillan with ipa, new oxford and yzkwEn

**Comment by StefanVukovic99** [comment]
The "yzk" dictionaries are obsoleted by this repo. The other two you mentioned need two fixes:
1. [v3 to v4 in index.json](https://github.com/themoeway/kaikki-to-yomitan/issues/10#issuecomment-1969991181)
2. have a script remove the last two fields in every entry. I added these to yezichak's v4 to hold deinflection information (though they weren't required), but that's done differently now in yomitan's v3 format.
```json
[
...
"", // remove
[] // remove 
]
```

**Comment by phamthaison1207** [comment]
How do I run these scripts for these dicts (sorry, I am not a programmer,
just a power user of these things, best thing I have done so far was just
editing 4 to 3)

**Comment by StefanVukovic99** [comment]
I've added a [v4 to v3 tool](https://github.com/themoeway/kaikki-to-yomitan/blob/master/tools/v4-to-v3.js). 
You paste a v4 zip in the same directory and run `node v4-to-v3.js DICTNAME.zip`

**Comment by jamesmaa** [comment]
Maybe it's worth cutting a new release with the fixed dictionary files?

**Comment by StefanVukovic99** [comment]
The dictionaries in the [release](https://github.com/themoeway/kaikki-to-yomitan/releases) should all work (and they replace the old yzk- dicts). Unfortunately there are a few older (and possibly proprietary) dicts that are in circulation, and the v4 to v3 stuff is for those few cases.

**Comment by jamesmaa** [comment]
I've been trying to import [kty-es-en.zip](https://github.com/themoeway/kaikki-to-yomitan/releases/download/beta/kty-es-en.zip) and see the `Error: Dictionary has invalid data in 'term_bank_10.json'`.

**Comment by StefanVukovic99** [comment]
Closing since there should be no more of these errors on the new stable releases.
